langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com/v1
      api-key: ${API_KEY:${API-KEY:}}
      model-name: deepseek-chat
      log-requests: true
      log-responses: true

rag:
  splitter:
    max-segment-size: 500
    max-overlap-size: 80
  retriever:
    min-score: 0.72
    max-results: 6

logging:
  level:
    dev.langchain4j: debug
    org.example.consultant: info